# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('courses_offered', multiselectfield.db.fields.MultiSelectField(choices=[('B.tech', 'B.tech'), ('diploma', 'Diploma'), ('mba', 'MBA'), ('pgdm', 'PGDM')], max_length=23)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.City')),
            ],
            options={
                'verbose_name_plural': 'Colleges',
                'verbose_name': 'College',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.City')),
            ],
        ),
    ]
