# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_city_college_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_offered', multiselectfield.db.fields.MultiSelectField(choices=[('B.tech', 'B.tech'), ('diploma', 'Diploma'), ('mba', 'MBA'), ('pgdm', 'PGDM')], max_length=23)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='selection.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='courses_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Courses'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
