# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_collegeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='level',
            field=models.CharField(choices=[('graduation', 'graduation'), ('post-graduation', 'post-graduation')], default='graduation', max_length=20),
        ),
    ]
