# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_college_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_offered',
            field=models.CharField(choices=[('B.tech', 'B.tech'), ('diploma', 'Diploma'), ('mba', 'MBA'), ('pgdm', 'PGDM')], max_length=40),
        ),
    ]
